export const ScreenNames = {
  LANDING_SCREEN: 'LandingScreen',
  LOGIN_SCREEN: 'LoginScreen',
  SIGNUP_SCREEN: 'SignupScreen',
  HOME_SCREEN: 'HomeScreen',
  GROCERY_SCREEN: 'GroceryScreen',
  GROCERY_LIST: 'GroceryList',
  PARCEL_SCREEN: 'ParcelScreen',
  SEND_PARCEL_SCREEN: 'SendParcelScreen',
  ADD_ADDRESS: 'AddAddress',
  DELIVERY_SCREEN: 'DeliveryScreen',
  PAYMENT_SCREEN: 'PaymentScreen',
  MY_PROFILE_SCREEN: 'MyProfileScreen',
  DRIVER_ONBOARDING_SCREEN: 'DriverOnboardingScreen',
  WEBVIEW_SCREEN: 'WebviewScreen',
  OPEN_TRIPS_SCREEN: 'OpenTripsScreen',
  ON_THE_MOVE_SCREEN: 'OnTheMoveScreen',
  ON_THE_RIDE_SCREEN: 'OnTheRideScreen',
  SUPPORT_SCREEN: 'SupportScreen',
  CAR_RENT_SCREEN: 'CarRentScreen',
  CAR_RENT_PICKUP_SCREEN: 'CarRentPickupScreen',
};
